# .github/workflows/deploy.yml
name: Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Vercel environment to deploy"
        required: true
        default: Preview
        type: choice
        options:
          - Production
          - Preview
      tag:
        description: "Git tag to deploy"
        required: true
        default: 0.2.0
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    env:
      VERCEL_ENVIRONMENT: ${{ inputs.environment || 'Preview' }}
      GIT_TAG: ${{ inputs.tag || '0.2.0' }}

    steps:
      - uses: actions/checkout@v4
      - run: npm install -g vercel
      - run: vercel pull --yes --environment=${{ env.VERCEL_ENVIRONMENT }} --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build ${{ env.VERCEL_ENVIRONMENT == 'Production' && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy --prebuilt ${{ env.VERCEL_ENVIRONMENT == 'Production' && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }}
